server:
  port: 19090

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        - id: order
          uri: lb://ORDER
          predicates:
            - Path=/api/orders/**
        - id: product
          uri: lb://PRODUCT
          predicates:
            - Path=/api/products/**
        - id: auth
          uri: lb://AUTH
          predicates:
            - Path=/api/auth/**
        - id: delivery
          uri: lb://DELIVERY
          predicates:
            - Path=/api/delivery/**
        - id: hub
          uri: lb://HUB
          predicates:
            - Path=/api/hubs/**
        - id: company
          uri: lb://COMPANY
          predicates:
            - Path=/api/companies/**
        - id: slack
          uri: lb://SLACK
          predicates:
            - Path=/api/slack/**
        - id: delivery-staffs
          uri: lb://AUTH
          predicates:
            - Path=/api/delivery-staffs/**
      discovery:
       locator:
        enabled: true

service:
  jwt:
    secret-key: ${SECRET_KEY}
