server:
  port: 19090 # Gateway 서비스 포트

spring:
  application:
    name: gateway-service # Eureka에 등록될 서비스 이름
  profiles:
    active:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Eureka 와의 통합 활성화
          lower-case-service-id: true # 서비스 ID를 소문자로 변환
      routes:
        - id: users-service
          uri: lb://users-service
          predicates:
            - Path=/users/**
    loadbalancer:
      retry: true # 로드 밸런싱 재시도 활성화
  discovery:
    client:
      service-url:
        defaultZone: http://localhost:19089/eureka/ # Eureka 서버 URL

eureka:
  client:
    register-with-eureka: false # Eureka 에 자신을 등록
    fetch-registry: false # Eureka 레지스트리를 가져옴
#  instance:
#    prefer-ip-address: true
