spring:
  application:
    name: delivery

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        auto-startup: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19089/eureka/
