naver:
  api:
    direction:
      url: "https://naveropenapi.apigw.ntruss.com/map-direction/v1/driving"
      headers:
        X-NCP-APIGW-API-KEY-ID: ${CLIENT_ID}
        X-NCP-APIGW-API-KEY: ${CLIENT_SECRET}
    geocoding:
      url: "https://naveropenapi.apigw.ntruss.com/map-geocode/v2/geocode"
      headers:
        X-NCP-APIGW-API-KEY-ID: ${GEO_CLIENT_ID}
        X-NCP-APIGW-API-KEY: ${GEO_CLIENT_SECRET}