server:
  port: 19090 # Gateway 서비스 포트
spring:
  profiles:
    active: dev
    application:
      name: auth-service # Eureka 에 등록될 서비스 이름

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19089/eureka/

service:
  jwt:
    access-expiration: 360000
    secret-key: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"